CREATE TABLE brands (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name text NOT NULL,
	status_id bool NULL DEFAULT true,
	
	created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	updated_at timestamp NULL,
	deleted_at timestamp NULL,
	created_by uuid NULL,
	updated_by uuid NULL,
	CONSTRAINT brands_pkey PRIMARY KEY (id)
);

CREATE TABLE categories (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name text NOT NULL,
	parent_id int NULL,
	sequence int NULL,
	status_id bool NULL DEFAULT true,

	created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	updated_at timestamp NULL,
	deleted_at timestamp NULL,
	created_by uuid NULL,
	updated_by uuid NULL,

	CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE suppliers (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name TEXT NOT NULL,
	email TEXT NULL,
	phone TEXT NULL,
	status_id bool NULL DEFAULT true,
	is_verified_supplier bool NULL DEFAULT true,

	created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	updated_at timestamp NULL,
	deleted_at timestamp NULL,
	created_by uuid NULL,
	updated_by uuid NULL,

	CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);

CREATE TABLE products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name TEXT NULL,
	description TEXT NULL,
	specifications TEXT NULL,
	brand_id INT NULL,
	category_id INT NULL,
	supplier_id INT NULL,
	unit_price INT NULL,
	discount_price INT NULL,
	tages text NULL,
	status_id bool NULL DEFAULT true,

    created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	updated_at timestamp NULL,
	deleted_at timestamp NULL,
	created_by uuid NULL,
	updated_by uuid NULL,

	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT brands_fk FOREIGN KEY (brand_id) REFERENCES public.brands(id),
	CONSTRAINT categories_fk FOREIGN KEY (category_id) REFERENCES public.categories(id)
	
);


CREATE TABLE product_stocks (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	product_id INT NOT NULL,
	stock_quantity INT NULL,
	created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	updated_at timestamp NULL,
	deleted_at timestamp NULL,
	created_by uuid NULL,
	updated_by uuid NULL,

	CONSTRAINT product_stock_pkey PRIMARY KEY (id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES public.products(id)
);