
DROP TABLE IF EXISTS product_stocks CASCADE; 
DROP TABLE IF EXISTS products CASCADE; 
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;  
DROP TABLE IF EXISTS brands CASCADE; 


